name: update_deno

on:
  workflow_dispatch:

jobs:
  build:
    name: update deno
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.DENOBOT_PAT }}
          submodules: recursive

      - name: Install deno
        uses: denoland/setup-deno@v1
